BrightspaceUILabs/navigation

- wct.conf.json
> Back to default version of Safari - sauce labs fix in

- demo/navigation-bottom-bar.html
> Improve demo for bottom bar

- d2l-navigation-shared-styles.html
- demo/d2l-navigation-button.html
- demo/navigation-band.html
- demo/navigation-main-footer.html
- demo/navigation-main-header.html
- demo/navigation-separator.html
- demo/navigation.html
- test/d2l-navigation-button.html
- test/navigation-band.html
- test/navigation-main-footer.html
- test/navigation-separator.html
- test/navigation.html
Not sure if all of these are necessary but adding in case
> Add strip whitespace for P3 conversion

- package.json
Applying the same change to the Polymer 3 branch (which will get thrown away and re-created later I'm assuming).
> fixing package name

- .eslintrc.json
- all-imports.html
- bower.json
- d2l-navigation-immersive.html
- d2l-navigation-link-back.html
- demo/d2l-navigation-button.html
- demo/navigation-immersive.html
Ready for initial review. Below is a screenshot of what the component looks like in a few states:
Design doc: http://design.d2l/components/immersive-navbar/
Please note that a lot of the design is out of scope for the first version (e.g. impersonation image) and the middle and right slots are intended to be filled out by the user of the component. So the title, separator, etc. are not part of the base component.
Still to do:
- unit tests
- readme updates
> d2l-navigation-immersive

- d2l-navigation-button.html
- demo/d2l-navigation-button.html
Found this while looking at Dave B's button highlight fix.  Might be specific to Firefox ESR, I'm not sure
Also removed the Firefox focus outline while I'm here.
> Fix Button Demo in Firefox

- d2l-navigation-button.html
- d2l-navigation-highlight-styles.html
- d2l-navigation-link-back.html
- d2l-navigation-link.html
Few issues I found when testing the Polymer 3 conversion
- Fix outline in Edge in Polymer 2 (and 3)
- Fix RTL padding in the navigation-link-back component
> Polymer 3 Prep

- package.json
Solves the issue I was having as described over here:
https://d2l.slack.com/archives/CDJE0AYMB/p1547753191076900
Finally got it 😄
> Specify lint folders as to not lint node_modules

- d2l-navigation-button-notification-icon.js
- d2l-navigation-button.js
- d2l-navigation-notification-icon.js
- test/d2l-navigation-button.html
US107607
https://github.com/BrightspaceUI/navigation/pull/69
> US107607 Made notification dot a component

- components/d2l-navigation-iterator/d2l-navigation-iterator.js
- components/d2l-navigation-iterator/d2l-navigation-link-iterator.js
- demo/d2l-navigation-iterator.html
- test/d2l-navigation-link-iterator.html
[US108899](https://rally1.rallydev.com/#/detail/userstory/324245903592?fdp=true): [UI] Add two onClick properties (one for previous, one for next) to d2l-navigation-iterator
> US108899 - Add on-click logic for previous and next 

- demo/navigation-immersive-demos/navigation-immersive-all-slots.html
Something like this.
Screenshot:
> Put iterator in the immersive nav right slot demo

- d2l-navigation-band.js
- d2l-navigation-shared-styles.js
We actually want the gradients to appear whether we are using our custom scrollbars or just the defaults for Mac and mobile - not sure what I was thinking!
> Apply the gradient for the default scrollbars as well

- package.json
Aligning the version with the latest tagged version. When I merge this, I'll try `[increment patch]` to see if it auto-bumps and releases properly.
> fixing version

- README.md
There's a lot of redundancy in this readme that could be cleaned up, but the goal of this PR is to try to remove the lies! 😈
> docs: Replace old readme instructions

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .stylelintrc.json
- d2l-navigation-separator.js
- d2l-navigation.js
- demo/button.html
- demo/immersive.html
- package.json
- test/immersive.visual-diff.html
Just dipping my toes in here with some easy ones -- `<d2l-navigation>` and `<d2l-navigation-separator>`.
> Lit Part 1

- d2l-navigation-separator.js
- d2l-navigation.js
- package.json
Just some prework before the work.
> fix: switch to main Lit package

- components/d2l-navigation-iterator/d2l-navigation-iterator.js
> fix: go back to the host being the flex container

- d2l-navigation-band.js
- d2l-navigation-shared-styles.js
- d2l-navigation-styles.js
- test/navigation.test.js
This migrates `<d2l-navigation-band>` to Lit. 🔥 
Not expecting any visual-diff changes here.
> feat: convert band to Lit

- README.md
Forgot to add `allow-overflow` to the readme in #213 ...
https://desire2learn.atlassian.net/browse/VOY-2250
> chore: Add allow-overflow to readme

- d2l-navigation-dropdown-button-custom.js
- d2l-navigation-dropdown-button-icon.js
- eslint.config.js
- package.json
- test/button.vdiff.js
Follow up PR to update dependencies now that polymer has been removed.
> fix: Update dependencies
