BrightspaceUILabs/navigation

- d2l-navigation-header.html
Just removing a redundant element. @jeroach, by default `:host` elements are `inline-block`, so if you want them to be anything other than that you need to specify it. In this case, we want the header to be a block element like a `<div>`.
> treating header host as a block element, removing need for a <div>

- bower.json
This is so you can go `bower link d2l-navigation` and have it actually work. :)
> name in bower.json should match registered name

- test/navigation-main-footer.html
- test/navigation-main-header.html
Have been trying to get slot asserts to work, unsuccessfully so far.
At least these asserts are better than the minimal check we had before.
> Add more assertion checks on the structure of the header and footer elements

- d2l-navigation-button-notification-icon.html
- d2l-navigation-button.html
- demo/d2l-navigation-button.html
- test/d2l-navigation-button.html
This fixes the NVDA screenreader problem we were seeing where the notification text was ignored.  It unfortunately only works in Shady DOM, because in Shadow DOM the button cannot see the `d2l-navigation-button`'s slot contents.
> Add aria-describedby to the button

- README.md
- d2l-navigation-immersive.html
- d2l-navigation-shared-styles.html
- d2l-navigation.html
- demo/navigation-immersive-demos/navigation-immersive-all-slots.html
- demo/navigation-immersive-demos/navigation-immersive-no-middle-slot.html
- demo/navigation-immersive-demos/navigation-immersive-no-slots.html
- demo/navigation-immersive.html
- wct.conf.json
This is a result of an issue we were seeing when trying to use the immersive nav in the Assignment Evaluations page, which has a fixed header.  Even with a `z-index` of `-100`, the gradient was overlappign the content below because the whole header is fixed. This is going to be an issue with everyone that wants the immersive nav to be sticky.  Since this is actually in the spec (http://design.d2l/components/immersive-navbar/) that the nav always be sticky, I think we should handle it here.  This PR:
- Adds `position: fixed` (not `sticky`, since that is not supported in IE11) to the immersive nav, sticking it to the top of the page
- Adjusts the demo page to be able to show and test this properly
- Exposes a new css variable `--d2l-navigation-shadow-gradient-display` that allows for the …
> Make d2l-navigation-immersive sticky

- d2l-navigation-immersive.html
- demo/navigation-immersive-demos/navigation-immersive-all-slots.html
- demo/navigation-immersive-demos/navigation-immersive-no-middle-slot.html
- demo/navigation-immersive-demos/navigation-immersive-no-slots.html
- test/navigation-immersive.html
Right now, consumers need to add a margin to the top of their page when using the immersive nav, so the start of the content is visible. Instead of having them worry about it (and the responsive rules), I'm adding a div here to take up the same amount of space as the header.  This will only work if the immersive nav element is the first visual element on the page, but that _should_ always be the case anyways and I'm good with enforcing that for now.
> Add div for spacing of the immersive nav

- d2l-navigation-immersive.html
- demo/navigation-immersive-demos/navigation-immersive-middle-slot-responsive.html
- demo/navigation-immersive.html
- test/navigation-immersive.html
Alternative to the fix we were trying to get working in https://github.com/BrightspaceUI/navigation/pull/48.  Edge is refusing to cooperate with `clientHeight` on a `slot`, so this is a bit of a redesign of the whole system.  We now have a div in the `d2l-navigation-immersive-middle` div that is only used to tell us the height of the slot's contents, and the `ResizeObserver` watches that instead.  We can use the `entries` array of the `ResizeObserver` now (before we couldn't because the `d2l-navigation-immersive-middle` had `height: 100%`, but we are now watching the new `div` with `height: auto`), so the code in `_onMiddleResize` can be simplified.
Still need to check the functionality and the tests on every browser!  But wanted to get the review up and sauce running.
> DE32394 - Fix Hiding of Middle Slot

- d2l-navigation-immersive.html
- demo/navigation-immersive-demos/navigation-immersive-all-slots.html
- demo/navigation-immersive-demos/navigation-immersive-middle-slot-responsive.html
- demo/navigation-immersive-demos/navigation-immersive-no-right-slot.html
- demo/navigation-immersive-demos/navigation-immersive-responsive-slot-hiding.html
- demo/navigation-immersive.html
- test/navigation-immersive.html
This is a use case the LE will be using, where the left slot has the back button and the middle slot has a title (until an iterator is eventually added in the future).  Spoke to Jeff G about the design of this and made adjustments accordingly.  The design now looks like this (the right slot takes up no space if it is empty, and the right separator is hidden):
~Still to do - Fixing and adding tests~ Done
> US103275 - Adjustments to the design when the right slot is empty

- d2l-navigation-link-image.html
Replaces [this code in BSI](https://github.com/Brightspace/brightspace-integration/blob/master/sass/navigation/logo.scss#L15), which wasn't working with shadow DOM anyway.
> supporting a slimmer logo for when there's a title

- d2l-navigation-main-footer.html
Moved these styles here [from here in BSI](https://github.com/Brightspace/brightspace-integration/blob/master/sass/navigation/main.scss#L21) now that the branding feature flag is always-ON.
> applying these styles now that the feature flag is always-on

- README.md
- d2l-navigation-immersive.html
- demo/navigation-immersive-demos/navigation-immersive-all-slots-max-width.html
- demo/navigation-immersive.html
While integrating the immersive nav into Brightspace for Parents, and Portfolio I noticed that the immersive nav wasn't aligning the back button with our page content.  I confirmed with @geurts that it should be aligned with the content.
In this pr I'm adding a css variable to allow the consumer to set the content max width.  Additionally it looks like my vscode normalized the line endings to LF in the files i've touched.
Demo image:
> Align Immersive navigation max-width to content max-width

- README.md
- d2l-navigation-immersive.js
- d2l-navigation-shared-styles.js
- d2l-navigation.js
- test/navigation.html
Design no longer wants this gradient below the navigation and immersive navigation.
Related PR in the LMS:
https://git.dev.d2l/projects/CORE/repos/le/pull-requests/15531/overview
> removing navigation gradient

- d2l-navigation-band.js
- d2l-navigation.js
- demo/navigation-band.html
- demo/navigation.html
Adding a slot to the navigation band so that we can render the consortium tabs
This allows for this:
> Slot in navigation band

- README.md
- d2l-navigation.js
This pull request adds the `--d2l-navigation-shadow-drop-border-display` CSS variable to allow the shadow to be hidden on specific pages.
> Add a CSS variable to allow the d2l-navigation shadow to be hidden

- d2l-navigation-immersive.js
This is the only change needed here, then I need to update the styles in LMS and we should get what is shown in the gif.
> Use min-width 0 so the middle slot knows its width

- .travis.yml
- README.md
I'm applying this everywhere -- this means you'll need to explicitly include `[increment whatever]` if you want the version to bump. This is more in line with how we want to be thoughtful about our semver changes in library repos like BrightspaceUI vs. FRAs which care a lot less.
> using new frau-ci release features

- README.md
- d2l-navigation-band.js
- d2l-navigation-shared-styles.js
- demo/navigation.html
- test/navigation-band.html
- Add custom scrollbar styles to the content inside the slot of the navigation band
- Only do so if we detect we are on a non-mobile Windows machine (want to leave the nice mobile and mac scrollbars alone)
> US109311 - Add Custom Scrollbars to Navigation Band for Org Tabs

- d2l-navigation-notification-icon.js
This will be used for the org tabs, but Jeff still wants the default to be 2px and the navigation buttons to use 2px, so they have not been updated to include this attribute.
(This file had mixed line endings, so look at the ignore whitespace diff).
> US109896 - Add the ability to use a thin (1px) border on the notification dot

- d2l-navigation-band.js
Don't let the gradients block from pressing the tab underneath
> Fix scrollbar gradients in navigation band

- d2l-navigation-band.js
- demo/navigation.html
This is the first of three PRs adding the ability for the selected tab to be scrolled into view and centered.
Since we can't use `ScrollIntoView` because that moves the focus in Chrome, we need to tell the `d2l-navigation-scroll` element where we want to go.  But only the contents of the slot know where we want to go, so this PR adds the ability for the `d2l-navigation-band` to receive an event (`d2l-navigation-band-slot-scroll-request`) with the location of the point that the nav-band should try to center.
> US111258 - Allow nav-band to listen for a scroll event

- d2l-navigation-link-image.js
- demo/index.html
- test/d2l-navigation-button.html
- test/d2l-navigation-iterator-item.html
- Added an index for the list of demo pages
- When passed an empty text value or missing text prop, `d2l-navigation-link-image` now creates inner `<img>` tag with `alt` attribute.
- Added test to confirm the above
- Refactored the button tests
- Tested code changes with BSI on a local lms instance
> De35352/Alt attribute on image with no link/text

- README.md
- d2l-navigation-immersive.js
- demo/navigation-immersive-demos/navigation-immersive-all-slots-width-type-normal.html
- demo/navigation-immersive.html
The user may now apply a `width-type` attribute on `d2l-navigation-immersive` with the value `normal`.
`normal` restricts the nav bar left/middle/right to fit a max-width of `1230px`.
The existing CSS variable, `--d2l-navigation-immersive-content-max-width` which allowed the user to configure the width to be any value will be removed. Usages of the existing CSS variable (2 places) will be updated accordingly to use the new attribute.
> Support a new `width-type` attribute

- .travis.yml
This switches the deployment to be a separate stage, which allows us to avoid the check to only run it in the visual-diff stage. It also lets us restrict the encrypted variables to the stages for which they're required.
> deploying as a separate stage

- d2l-navigation-immersive.js
Not sure how this happened, but these 2 properties were [accidentally deleted](https://github.com/BrightspaceUI/navigation/commit/74425b5736614d97a39e91cfc3322ab3ae4b5df0#diff-be945901e9cdfaab1afb2753c6bb090a) last July. Restoring them.
> restoring back-link-href and back-link-text properties

- d2l-navigation-main-footer.js
- test/navigation-main-footer.html
We had a defect recently where the "..." more menu in the Brightspace navbar was suddenly always showing up and wasn't obeying the "visible-on-ancestor" behaviour.
Turns out the timing around how this stuff wires up is very delicate, and unbundled BSI builds were initializing faster such that `<d2l-navigation-main-footer>`'s shadow root wasn't available yet when the descendants initialized. The solution was to simply move the `visible-on-ancesator-target` CSS class to an element that isn't in the shadow root, [like this](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/14251/overview).
In doing so, having it also be applied here isn't necessary. Also... I don't really think it's `navigation-main-footer`'s responsibility to even know about this, since it has no idea what's being …
> removing visible-on-ancestor parent from nav

- d2l-navigation-link-back.js
Noticed that when things get tight, the back-link can wrap both inside the text but also the text can wrap on a different line from the back chevron icon. Since these are always used inside the navigation header, I don't think we ever want wrapping.
> prevent back link text & icon from wrapping

- d2l-navigation-immersive.js
@Vitalii-Misechko noticed that when immersive nav (`z-index: 1`) is used with skeleton loaders (`z-index: 1`), when you scroll the page such that the skeletons are "behind" the immersive nav, whichever rendered last "wins" the z-index tie and is displayed on top:
Increasing immersive nav to `z-index: 2` solves the problem. The band also uses `z-index: 2` for the scrolling gradient, but as far as I can tell bands with stuff inside them that might scroll and immersive nav can't be used together. Does that sound right Stacey?
> increasing z-index on immersive nav to be higher than skeleton loaders

- .travis.yml
- package.json
`visual-diff` has puppeteer as a peer dependency, which gets installed as of NPM 7 and is conflicting.
> upgrading to puppeteer 5

- d2l-navigation-button.js
This is the default behavior on the iterator when hovering over the button. See the blue bar at the top
This is what design has asked for when the button is used not at the top of the page. No blue bar at the top
> d2l-navigation-button - Add property to remove top bar

- .github/workflows/main.yml
- .github/workflows/test-aws.js
This will be deleted after I see everything is working, but I can't test this in my fork.  This tests whether I can assume the role successfully with the rotated secrets and then lists out the first item in the bucket (which should be the screenshots folder).
> Adding a simple workflow to test the setup of the AWS role and token rotator

- .github/workflows/ci.yml
This was done as an experiment to see how the timing compared to having it in its separate `visual-diff.yml` workflow. We've decided we like having the separate workflow better as it allows the tests to run in parallel and they can also be re-runnable.
> ci: remove visual-diff from CI workflow

- d2l-navigation-immersive.js
During FACE development, when trying to add a title to the immersive navigation bar, we noticed that the immersive navigation bar doesn't take into account RTL as the divider between the "Back to {Activity}" button and "Title" renders properly in LTR but disappears in RTL languages. The reason is because we're setting `border-right: none` on `.d2l-navigation-immersive-middle` regardless of language.
_Notice the divider is rendered on the left_
* Added mixin behaviour to `d2l-navigation-immersive` so that it inherits the `dir` attribute with value equal to either `ltr` or `rtl`
* Added CSS selector to apply the right styling to the host when the locale is a `rtl` language
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F461506956220&fdp=true?fdp=true …
> Enabled immersive nav view to handle RTL

- .gitattributes
- .github/CODEOWNERS
- .npmignore
- .npmrc
- CODEOWNERS
- components/d2l-navigation-iterator/d2l-navigation-iterator-item.js
- d2l-navigation-band.js
- d2l-navigation-button-close.js
- d2l-navigation-button-notification-icon.js
- d2l-navigation-highlight-styles.js
- d2l-navigation-immersive.js
- d2l-navigation-link-back.js
- d2l-navigation-main-footer.js
- d2l-navigation-notification-icon.js
- d2l-navigation-separator.js
- demo/d2l-navigation-button.html
- package.json
- test/d2l-navigation-iterator-item.html
The ones removed were all drop in replacements. The ones not removed used various style shims or polymer behaviours that can't be removed at the moment. Doing this as part of an effort to minimize github/git style dependency refs in package.json files. NPM 8 has issues with them and can greatly increase install time (`d2l-rubric` takes 2 min to install with NPM 6 and without any changes takes 30 min with NPM 8).
> feat: switch to use `core` for several components

- package.json
This PR makes the breaking changes required to update to Lit 2 (`lit-html` 2 and `lit-element` 3). The Lit 2 upgrade will be a coordinated effort, so **this PR should not merge at this time**.
Breaking change checklist: 
Renamed API's:
Testing checklist: 
For more information on the Lit 2 upgrade, visit https://lit.dev/docs/releases/upgrade/ or contact team Gaudi.
> BREAKING CHANGE: Lit 2 upgrade

- d2l-navigation-link.js
This is a regression from #134. In the link behavior that was removed, [it was setting](https://github.com/BrightspaceUI/link/blob/master/d2l-link-behavior.js#L25) `reflectToAttribute: true` on the `href` attribute. That was lost... which normally probably wouldn't matter, except that `d2l-navigation-link` has this CSS:
```css
:host(:not([href])) a {
cursor: default;
}
```
So if the host doesn't have an `href`, the cursor is reset on the `<a>`. Not sure why that's there and why it wouldn't just _not_ have an `<a>` if there's no `href`, but probably the answer is "Polymer".
This defect didn't escape into the June release, so just July.
> fix: link cursor

- d2l-navigation-link-image.js
- package.json
Another simple one, this migrates `<d2l-navigation-link-image>` to Lit by leveraging the shared link styles.
Not expecting any visual diffs here. 🤞
> Lit conversion of d2l-navigation-link-image

- d2l-navigation-button-icon.js
Forgot that for some silly reason, `<button>`'s `type` defaults to `submit`, which means pressing ENTER on this button would submit any forms that were on the page. We want these to be standard `button` types.
> fix: set type for button

- d2l-navigation-button-icon.js
Small fix that I think we want everywhere, but it also resolves this crazy issue in sequences:
The issue there is that the target for the tooltip actually moves when the sidebar opens, and tooltip really has no mechanism to know that this happened and reposition itself. `ResizeObserver` and `MutationObserver` don't fire when things move, only when they change size or mutate. Either way, I still think just hiding the tooltip on-click is a nicer experience anyway.
After:
> fix: close tooltips when buttons are clicked

- d2l-navigation-link-icon.js
Missed this one compared to the others -- we always want these opening down otherwise they open to the right on cover over other things in the nav.
> fix: tooltip position

- components/d2l-navigation-iterator/d2l-navigation-iterator.js
Cert version of this fix: https://github.com/BrightspaceUILabs/navigation/pull/171
In the [pre-Lit Polymer version](https://github.com/BrightspaceUILabs/navigation/blob/d4ca49dec78b0d4b2c7fcfdd0b06cf6332267cad/components/d2l-navigation-iterator/d2l-navigation-iterator.js#L39) of this component, the `flex` was applied to the host. But because it was also apply a Polymer style mixin that I couldn't use in Lit, I moved all of that CSS to a container where I could apply "compact text" styles.
Unfortunately, there was [code in the LMS](https://search.d2l.dev/xref/lms/lp/framework/web/D2L.LP.Web.UI/Desktop/Controls/ImmersiveNav/ImmersiveNav.css?r=0136e0e3#32) applying some negative margins that did some funky stuff to the non-flex element:
So I'm reverting back to applying the flex to the host, …
> fix: go back to the host being the flex container

- README.md
I've added how to `npm install` this repo since it was missing and also corrected the import for the `d2l-navigation-iterator` component.
> Fix d2l-navigation-iterator import

- d2l-navigation-button-icon.js
- d2l-navigation-dropdown-button-icon.js
- d2l-navigation-link-icon.js
- d2l-navigation-link-image.js
Adding `tooltip-offset` attribute to all components that internally use `<d2l-tooltip>`. The goal is to set this offset to 0 for navigation items on the main page of the LMS, per the [design specs](https://www.figma.com/proto/jxxWTG3fC0nNPgvECXcZ0D/Tooltips---Improved-Contrast?page-id=0%3A1&node-id=2%3A48&viewport=-875%2C658%2C0.39&scaling=min-zoom&starting-point-node-id=2%3A48).
Rally: https://rally1.rallydev.com/#/?detail=/defect/645635571497&fdp=true
> feat: Add tooltipOffset

- demo/navigation.html
The `d2l-demo-snippet` attribute `fullscreen` is being renamed to full-width. These changes will need to happen more or less at the same time as core is updated.
Once the changes are released in `core` this PR will be updated to bump the dependency version.
BrightspaceUI/core#2926
[US144714](https://rally1.rallydev.com/#/?detail=/userstory/665191647783&fdp=true): Add fullscreen switch to d2l-demo-snippet
> Update d2l-demo-snippet fullscreen to full-width

- README.md
- d2l-navigation-button-icon.js
[DE51509](https://rally1.rallydev.com/#/42960320374ud/custom/236803223728?detail=%2Fdefect%2F675164753105): Tool tip for iterating between students in CE is cut off
Pairs with this PR:
* https://github.com/Brightspace/consistent-evaluation/pull/1631
> DE51509 - add tooltip-position property to d2l-navigation-button-icon

- test/button.test.js
- test/immersive.test.js
- test/iterator.test.js
- test/link.test.js
- test/navigation.test.js
Had this on a to do list for a while lol. This repo uses `@brightspace-ui/testing`, so it can just get `runConstructor` from there. Someday, we'll want to remove the one in `core`.
> Remove constructor-test-helper reference

- .npmrc
Mostly just want to regenerate the vdiffs so I can be confident my Lit migration isn't causing issues.
This isn't needed since the lock file is already excluded in `.gitignore` and is preventing one from being created in the first place.
> remove npmrc

- d2l-navigation-immersive.js
- d2l-navigation-main-footer.js
- d2l-navigation-main-header.js
- d2l-navigation-shared-styles.js
This migrates the header, footer and "immersive" elements from Polymer to Lit. I needed to make an update to the immersive element, so figured this was worth it.
> Migrate some nav elements to Lit

- d2l-navigation-immersive.js
- test/immersive.test.js
Two of the Insights usages ([example](https://github.com/Brightspace/insights-adoption-dashboard/blob/a5904fc9881fbc12bb65f97bbe1c1a8863afe2cb/insights-adoption-dashboard.js#L142)) are wiring up to a click event handler on the back link to apply some extra logic. This adds an event for them to do that.
> GAUD-6565: add back link click event

- package.json
No longer needed after the Lit conversion.
> fix: remove unused dependencies
